export const MockResponse = {
  location: {
    name: 'Cairo',
    region: 'Tacna',
    country: 'Peru',
    lat: -17.47,
    lon: -70.55,
    tz_id: 'America/Lima',
    localtime_epoch: 1700035790,
    localtime: '2023-11-15 3:09',
  },
  current: {
    last_updated_epoch: 1700035200,
    last_updated: '2023-11-15 03:00',
    temp_c: 16.0,
    temp_f: 60.9,
    is_day: 0,
    condition: {
      text: 'Partly cloudy',
      icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
      code: 1003,
    },
    wind_mph: 2.2,
    wind_kph: 3.6,
    wind_degree: 227,
    wind_dir: 'SW',
    pressure_mb: 1012.0,
    pressure_in: 29.89,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 84,
    cloud: 33,
    feelslike_c: 16.0,
    feelslike_f: 60.9,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 1.0,
    gust_mph: 1.3,
    gust_kph: 2.1,
  },
  forecast: {
    forecastday: [
      {
        date: '2023-11-15',
        date_epoch: 1700006400,
        day: {
          maxtemp_c: 22.2,
          maxtemp_f: 71.9,
          mintemp_c: 14.8,
          mintemp_f: 58.7,
          avgtemp_c: 17.6,
          avgtemp_f: 63.8,
          maxwind_mph: 10.7,
          maxwind_kph: 17.3,
          totalprecip_mm: 0.01,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 75.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000,
          },
          uv: 5.0,
        },
        astro: {
          sunrise: '05:00 AM',
          sunset: '05:56 PM',
          moonrise: '06:38 AM',
          moonset: '08:26 PM',
          moon_phase: 'Waxing Crescent',
          moon_illumination: 3,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1700024400,
            time: '2023-11-15 00:00',
            temp_c: 15.5,
            temp_f: 59.9,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 174,
            wind_dir: 'S',
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 88,
            cloud: 59,
            feelslike_c: 15.5,
            feelslike_f: 59.9,
            windchill_c: 15.5,
            windchill_f: 59.9,
            heatindex_c: 15.5,
            heatindex_f: 59.9,
            dewpoint_c: 13.5,
            dewpoint_f: 56.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.6,
            gust_kph: 4.1,
            uv: 1.0,
          },
          {
            time_epoch: 1700028000,
            time: '2023-11-15 01:00',
            temp_c: 15.4,
            temp_f: 59.8,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 168,
            wind_dir: 'SSE',
            pressure_mb: 1013.0,
            pressure_in: 29.92,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 54,
            feelslike_c: 15.5,
            feelslike_f: 59.8,
            windchill_c: 15.5,
            windchill_f: 59.8,
            heatindex_c: 15.5,
            heatindex_f: 59.8,
            dewpoint_c: 13.4,
            dewpoint_f: 56.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.1,
            gust_kph: 5.0,
            uv: 1.0,
          },
          {
            time_epoch: 1700031600,
            time: '2023-11-15 02:00',
            temp_c: 15.5,
            temp_f: 60.0,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 87,
            wind_dir: 'E',
            pressure_mb: 1012.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 53,
            feelslike_c: 15.5,
            feelslike_f: 60.0,
            windchill_c: 15.5,
            windchill_f: 60.0,
            heatindex_c: 15.5,
            heatindex_f: 60.0,
            dewpoint_c: 13.3,
            dewpoint_f: 56.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 1.5,
            gust_kph: 2.5,
            uv: 1.0,
          },
          {
            time_epoch: 1700035200,
            time: '2023-11-15 03:00',
            temp_c: 16.0,
            temp_f: 60.9,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 227,
            wind_dir: 'SW',
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 84,
            cloud: 33,
            feelslike_c: 16.0,
            feelslike_f: 60.9,
            windchill_c: 16.0,
            windchill_f: 60.9,
            heatindex_c: 16.0,
            heatindex_f: 60.9,
            dewpoint_c: 13.3,
            dewpoint_f: 56.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 1.3,
            gust_kph: 2.1,
            uv: 1.0,
          },
          {
            time_epoch: 1700038800,
            time: '2023-11-15 04:00',
            temp_c: 15.7,
            temp_f: 60.2,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 214,
            wind_dir: 'SW',
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 34,
            feelslike_c: 15.7,
            feelslike_f: 60.2,
            windchill_c: 15.7,
            windchill_f: 60.2,
            heatindex_c: 15.7,
            heatindex_f: 60.2,
            dewpoint_c: 13.4,
            dewpoint_f: 56.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.3,
            gust_kph: 8.5,
            uv: 1.0,
          },
          {
            time_epoch: 1700042400,
            time: '2023-11-15 05:00',
            temp_c: 14.8,
            temp_f: 58.7,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 190,
            wind_dir: 'S',
            pressure_mb: 1014.0,
            pressure_in: 29.93,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 92,
            cloud: 63,
            feelslike_c: 15.1,
            feelslike_f: 59.1,
            windchill_c: 15.1,
            windchill_f: 59.1,
            heatindex_c: 14.8,
            heatindex_f: 58.7,
            dewpoint_c: 13.6,
            dewpoint_f: 56.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.3,
            gust_kph: 6.9,
            uv: 1.0,
          },
          {
            time_epoch: 1700046000,
            time: '2023-11-15 06:00',
            temp_c: 15.4,
            temp_f: 59.7,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 151,
            wind_dir: 'SSE',
            pressure_mb: 1014.0,
            pressure_in: 29.95,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 88,
            cloud: 49,
            feelslike_c: 15.4,
            feelslike_f: 59.7,
            windchill_c: 15.4,
            windchill_f: 59.7,
            heatindex_c: 15.4,
            heatindex_f: 59.7,
            dewpoint_c: 13.5,
            dewpoint_f: 56.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 2.6,
            gust_kph: 4.1,
            uv: 5.0,
          },
          {
            time_epoch: 1700049600,
            time: '2023-11-15 07:00',
            temp_c: 16.5,
            temp_f: 61.6,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 177,
            wind_dir: 'S',
            pressure_mb: 1014.0,
            pressure_in: 29.95,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 82,
            cloud: 40,
            feelslike_c: 16.5,
            feelslike_f: 61.6,
            windchill_c: 16.5,
            windchill_f: 61.6,
            heatindex_c: 16.5,
            heatindex_f: 61.6,
            dewpoint_c: 13.4,
            dewpoint_f: 56.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 5.0,
          },
          {
            time_epoch: 1700053200,
            time: '2023-11-15 08:00',
            temp_c: 18.0,
            temp_f: 64.4,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 190,
            wind_dir: 'S',
            pressure_mb: 1014.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 14,
            feelslike_c: 18.0,
            feelslike_f: 64.4,
            windchill_c: 18.0,
            windchill_f: 64.4,
            heatindex_c: 18.0,
            heatindex_f: 64.4,
            dewpoint_c: 13.4,
            dewpoint_f: 56.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.7,
            gust_kph: 9.1,
            uv: 5.0,
          },
          {
            time_epoch: 1700056800,
            time: '2023-11-15 09:00',
            temp_c: 17.5,
            temp_f: 63.5,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 189,
            wind_dir: 'S',
            pressure_mb: 1014.0,
            pressure_in: 29.95,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 3,
            feelslike_c: 17.5,
            feelslike_f: 63.5,
            windchill_c: 17.5,
            windchill_f: 63.5,
            heatindex_c: 17.5,
            heatindex_f: 63.5,
            dewpoint_c: 11.4,
            dewpoint_f: 52.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.9,
            gust_kph: 11.1,
            uv: 5.0,
          },
          {
            time_epoch: 1700060400,
            time: '2023-11-15 10:00',
            temp_c: 19.3,
            temp_f: 66.7,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 192,
            wind_dir: 'SSW',
            pressure_mb: 1013.0,
            pressure_in: 29.92,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 1,
            feelslike_c: 19.3,
            feelslike_f: 66.7,
            windchill_c: 19.3,
            windchill_f: 66.7,
            heatindex_c: 19.3,
            heatindex_f: 66.7,
            dewpoint_c: 11.2,
            dewpoint_f: 52.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.8,
            gust_kph: 15.7,
            uv: 5.0,
          },
          {
            time_epoch: 1700064000,
            time: '2023-11-15 11:00',
            temp_c: 20.6,
            temp_f: 69.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 188,
            wind_dir: 'S',
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 2,
            feelslike_c: 20.6,
            feelslike_f: 69.1,
            windchill_c: 20.6,
            windchill_f: 69.1,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 11.3,
            dewpoint_f: 52.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.4,
            gust_kph: 18.4,
            uv: 6.0,
          },
          {
            time_epoch: 1700067600,
            time: '2023-11-15 12:00',
            temp_c: 21.1,
            temp_f: 70.0,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 184,
            wind_dir: 'S',
            pressure_mb: 1013.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 54,
            cloud: 2,
            feelslike_c: 21.1,
            feelslike_f: 70.0,
            windchill_c: 21.1,
            windchill_f: 70.0,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 11.5,
            dewpoint_f: 52.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.4,
            gust_kph: 18.3,
            uv: 6.0,
          },
          {
            time_epoch: 1700071200,
            time: '2023-11-15 13:00',
            temp_c: 22.2,
            temp_f: 71.9,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 188,
            wind_dir: 'S',
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 17,
            feelslike_c: 24.5,
            feelslike_f: 76.1,
            windchill_c: 22.2,
            windchill_f: 71.9,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 11.8,
            dewpoint_f: 53.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.8,
            gust_kph: 19.0,
            uv: 6.0,
          },
          {
            time_epoch: 1700074800,
            time: '2023-11-15 14:00',
            temp_c: 21.7,
            temp_f: 71.0,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 189,
            wind_dir: 'S',
            pressure_mb: 1012.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 22,
            feelslike_c: 21.7,
            feelslike_f: 71.0,
            windchill_c: 21.7,
            windchill_f: 71.0,
            heatindex_c: 24.5,
            heatindex_f: 76.0,
            dewpoint_c: 12.2,
            dewpoint_f: 53.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.3,
            gust_kph: 19.9,
            uv: 6.0,
          },
          {
            time_epoch: 1700078400,
            time: '2023-11-15 15:00',
            temp_c: 20.7,
            temp_f: 69.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 185,
            wind_dir: 'S',
            pressure_mb: 1012.0,
            pressure_in: 29.88,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 4,
            feelslike_c: 20.7,
            feelslike_f: 69.2,
            windchill_c: 20.7,
            windchill_f: 69.2,
            heatindex_c: 20.7,
            heatindex_f: 69.2,
            dewpoint_c: 12.5,
            dewpoint_f: 54.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.6,
            gust_kph: 17.0,
            uv: 6.0,
          },
          {
            time_epoch: 1700082000,
            time: '2023-11-15 16:00',
            temp_c: 19.3,
            temp_f: 66.8,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 178,
            wind_dir: 'S',
            pressure_mb: 1012.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 55,
            feelslike_c: 19.3,
            feelslike_f: 66.8,
            windchill_c: 19.3,
            windchill_f: 66.8,
            heatindex_c: 19.3,
            heatindex_f: 66.8,
            dewpoint_c: 12.4,
            dewpoint_f: 54.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.5,
            gust_kph: 13.8,
            uv: 5.0,
          },
          {
            time_epoch: 1700085600,
            time: '2023-11-15 17:00',
            temp_c: 18.7,
            temp_f: 65.7,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 172,
            wind_dir: 'S',
            pressure_mb: 1013.0,
            pressure_in: 29.91,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 68,
            cloud: 18,
            feelslike_c: 18.7,
            feelslike_f: 65.7,
            windchill_c: 18.7,
            windchill_f: 65.7,
            heatindex_c: 18.7,
            heatindex_f: 65.7,
            dewpoint_c: 12.7,
            dewpoint_f: 54.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.8,
            gust_kph: 11.0,
            uv: 5.0,
          },
          {
            time_epoch: 1700089200,
            time: '2023-11-15 18:00',
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 166,
            wind_dir: 'SSE',
            pressure_mb: 1013.0,
            pressure_in: 29.93,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 73,
            cloud: 2,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 13.1,
            dewpoint_f: 55.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.2,
            gust_kph: 10.0,
            uv: 1.0,
          },
          {
            time_epoch: 1700092800,
            time: '2023-11-15 19:00',
            temp_c: 17.4,
            temp_f: 63.4,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 162,
            wind_dir: 'SSE',
            pressure_mb: 1014.0,
            pressure_in: 29.95,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 78,
            cloud: 10,
            feelslike_c: 17.5,
            feelslike_f: 63.4,
            windchill_c: 17.5,
            windchill_f: 63.4,
            heatindex_c: 17.5,
            heatindex_f: 63.4,
            dewpoint_c: 13.6,
            dewpoint_f: 56.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 1.0,
          },
          {
            time_epoch: 1700096400,
            time: '2023-11-15 20:00',
            temp_c: 16.8,
            temp_f: 62.2,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 190,
            wind_dir: 'S',
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 81,
            cloud: 17,
            feelslike_c: 16.8,
            feelslike_f: 62.2,
            windchill_c: 16.8,
            windchill_f: 62.2,
            heatindex_c: 16.8,
            heatindex_f: 62.2,
            dewpoint_c: 13.6,
            dewpoint_f: 56.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 1.0,
          },
          {
            time_epoch: 1700100000,
            time: '2023-11-15 21:00',
            temp_c: 16.0,
            temp_f: 60.9,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 165,
            wind_dir: 'SSE',
            pressure_mb: 1016.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 40,
            feelslike_c: 16.0,
            feelslike_f: 60.9,
            windchill_c: 16.0,
            windchill_f: 60.9,
            heatindex_c: 16.0,
            heatindex_f: 60.9,
            dewpoint_c: 13.6,
            dewpoint_f: 56.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.1,
            gust_kph: 6.6,
            uv: 1.0,
          },
          {
            time_epoch: 1700103600,
            time: '2023-11-15 22:00',
            temp_c: 15.7,
            temp_f: 60.2,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 142,
            wind_dir: 'SE',
            pressure_mb: 1016.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 86,
            cloud: 32,
            feelslike_c: 15.7,
            feelslike_f: 60.2,
            windchill_c: 15.7,
            windchill_f: 60.2,
            heatindex_c: 15.7,
            heatindex_f: 60.2,
            dewpoint_c: 13.3,
            dewpoint_f: 55.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.4,
            gust_kph: 5.5,
            uv: 1.0,
          },
          {
            time_epoch: 1700107200,
            time: '2023-11-15 23:00',
            temp_c: 15.6,
            temp_f: 60.2,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 152,
            wind_dir: 'SSE',
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 45,
            feelslike_c: 15.6,
            feelslike_f: 60.2,
            windchill_c: 15.6,
            windchill_f: 60.2,
            heatindex_c: 15.6,
            heatindex_f: 60.2,
            dewpoint_c: 13.4,
            dewpoint_f: 56.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 1.0,
          },
        ],
      },
    ],
  },
};
